apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "uv-portal-desktop.labels"  . | nindent 4 }}
  name: system-consts
  namespace: {{ include "uv-portal-desktop.namespace" . }}
data:
{{- .Values.systemConsts.configMapData | toYaml | nindent 2 }}
