replicaCount: 1

imagePullSecrets:
  - name: regcred

image:
  repository: 230690759643.dkr.ecr.eu-west-1.amazonaws.com/vnc-desktop
  tag: ''

namespace: uveye

resources:
  limits:
    memory: 4096Mi
    cpu: "2"
  requests:
    memory: 512Mi
    cpu: "0.4"
    
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: In
              values:
                - "true"

service:
  enabled: true
  type: LoadBalancer

env:
  - name: USER
    value: uvdesk
  - name: VNC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: secrets-uv-portal-vnc-desktop
        key: password
  - name: HTTP_PASSWORD
    valueFrom:
      secretKeyRef:
        name: secrets-uv-portal-vnc-desktop
        key: password
  - name: PASSWORD
    valueFrom:
      secretKeyRef:
        name: secrets-uv-portal-vnc-desktop
        key: password
  - name: DISPLAY
    value: ":1.0"

livenessProbe: {}
readinessProbe: {}

systemConsts:
  configMapData:
    supervisord.conf: |-
        [supervisord]
        redirect_stderr=true
        stopsignal=QUIT
        autorestart=true
        directory=/root
        #
        [program:nginx]
        priority=10
        command=nginx -c /etc/nginx/nginx.conf -g 'daemon off;'
        #
        [program:web]
        priority=10
        directory=/usr/local/lib/web/backend
        command=/usr/local/lib/web/backend/run.py
        stdout_logfile=/dev/fd/1
        stdout_logfile_maxbytes=0
        stderr_logfile=/dev/fd/1
        stderr_logfile_maxbytes=0
        #
        #
        [group:x]
        programs=xvfb,wm,lxpanel,pcmanfm,x11vnc,novnc
        #
        [program:wm]
        priority=15
        command=/usr/bin/openbox
        environment=DISPLAY=":1",HOME="/root",USER="root"
        #
        [program:lxpanel]
        priority=15
        directory=/home/uvdesk
        command=/usr/bin/lxpanel --profile LXDE
        user=uvdesk
        environment=DISPLAY=":1",HOME="/home/uvdesk",USER="uvdesk"
        #
        [program:pcmanfm]
        priority=15
        directory=/home/uvdesk
        command=/usr/bin/pcmanfm --desktop --profile LXDE
        user=uvdesk
        environment=DISPLAY=":1",HOME="/home/uvdesk",USER="uvdesk"
        #
        [program:xvfb]
        priority=10
        command=/usr/local/bin/xvfb.sh
        stopsignal=KILL
        #
        [program:x11vnc]
        priority=20
        command=x11vnc -display :1 -xkb -forever -shared -repeat -capslock -rfbauth /.password2
        #
        [program:novnc]
        priority=25
        directory=/usr/local/lib/web/frontend/static/novnc
        command=bash /usr/local/lib/web/frontend/static/novnc/utils/launch.sh --listen 6081
        stopasgroup=true
        #

